### ISSUE TITLE
Java 8 Requirement

### ISSUE THREAD

**Issue by tliebeck** [rapid7/smbj-rpc#12]
Recent builds are requiring Java 8, with the only actual Java 8 usage being an interface with defaults (com.rapid7.client.dcerpc.io.Hexify) and a couple of lambda expressions in a test (com.rapid7.client.dcerpc.transport.Test_RPCTransport).  

As I'm developing an app for Android, I'm having to remove these before I can use this library.  Is there any chance at retaining Java 7 compatibility?

Thanks for all your hard work!

**Comment by bli-r7** [comment]
@tliebeck I'll take a stab at this.

**Comment by bli-r7** [comment]
@tliebeck The master branch should be java7 compatible now.
