### ISSUE TITLE
ServerService permission denied with level 2 NetShareEnumRequest

### ISSUE THREAD

**Issue by tliebeck** [rapid7/smbj-rpc#13]
I'm having to modify ServerService.java and change the NetrShareEnumRequest level from '2' to '1' in order to successfully get a share listing from a Windows 7 machine, Windows 10 machine, and a Mac running Sierra.  The Win10 machine is completely stock, i.e., a fresh VM downloaded from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/   Without this change I get a permission denied.  Share listings work fine with level '2' against Ubuntu 16.04.

    diff --git a/src/main/java/com/rapid7/client/dcerpc/mssrvs/ServerService.java b/src/main/java/com/rapid7/client/dcerpc/mssrvs/ServerService.java
    index 1b8587b..d4e5b49 100644
    --- a/src/main/java/com/rapid7/client/dcerpc/mssrvs/ServerService.java
    +++ b/src/main/java/com/rapid7/client/dcerpc/mssrvs/ServerService.java
    @@ -51,7 +51,7 @@ public class ServerService {
             final List<NetShareInfo0> shares = new LinkedList<>();
             final MutableInt resumeHandle = new MutableInt();
             for (;;) {
    -            final NetrShareEnumRequest request = new NetrShareEnumRequest(2, resumeHandle.getValue());
    +            final NetrShareEnumRequest request = new NetrShareEnumRequest(1, resumeHandle.getValue());
                 final NetrShareEnumResponse response = transport.call(request);
                 final int returnCode = response.getReturnValue();
                 if (SystemErrorCode.ERROR_SUCCESS.is(returnCode) || SystemErrorCode.ERROR_MORE_DATA.is(returnCode)) {

**Comment by skhare-r7** [comment]
Interesting, does the information level available depend on Administrative credentials / special privileges?

**Comment by bli-r7** [comment]
@tliebeck 
Does the credential you were using has the required privilege?

See https://msdn.microsoft.com/en-us/library/cc247297.aspx#Appendix_A_58
<60> Section 3.1.4.10: If the requested level is 2, 502, or 503, the Windows implementation checks to see whether the caller is in the Administrators, Server or Print Operators, or Power Users local group. No special group membership is required for other levels.

**Comment by bli-r7** [comment]
@tliebeck opened https://github.com/rapid7/smbj-rpc/issues/30 to address this.
