### ISSUE TITLE
How should I include this library in android studio?

### ISSUE THREAD

**Issue by shahvir** [rapid7/smbj-rpc#138]
I did not find any JAR file and could not find a guide on how to include the library in project. Any help is appreciated.

**Comment by tosmun-r7** [comment]
You can find the releases on mavencentral: https://search.maven.org/artifact/com.rapid7.client/dcerpc/0.10.0/jar

**Comment by shahvir** [comment]
Thanks Taylor.
I have another question. I used the library to get all the shares, but I  I
only need the printers. Is there any way I can decide if a share is a
printer?

**Comment by asmith-r7** [comment]
solution above
