### ISSUE TITLE
Is RPC implementation tightly bound to smb version 2 or it depends on  smbj?

### ISSUE THREAD

**Issue by kvk484** [rapid7/smbj-rpc#149]
Hi
Is RPC implementation tightly bound to smb version 2 or it depends on  smbj?

**Comment by rkirk-r7** [comment]
Yes the SMB version depends on the underlying support from smbj. Currently this library only works with smbj versions that support SMB v2. Updates will be coming to support newer smbj releases which support SMBv3 dialects.
