### ISSUE TITLE
smbj dependancy conflicts

### ISSUE THREAD

**Issue by felixRajkumar** [rapid7/smbj-rpc#152]
Hi, 
    On using the smbj latest version with dcerpc, it seems there are conflicting code changes with respect to the new version of smbj. Are you planning to release new version with respect to the new smbj jar.

**Comment by rkirk-r7** [comment]
Moved to smbj 0.10.0 in latest release https://github.com/rapid7/smbj-rpc/releases/tag/dcerpc-0.11.0.  We intend to release support for newer smbj versions but do not have an ETA as yet
