### ISSUE TITLE
Can't pass or stop "SMBTransportFactories.SRVSVC.getTransport(mSession);"

### ISSUE THREAD

**Issue by abigliar** [rapid7/smbj-rpc#164]
I updated my project to rapid7/smbj-rpc 0.11.0, and my Android "SMB file explorer" app running "RPCTransport transport = SMBTransportFactories.SRVSVC.getTransport(mSession);" all the time.

It doesn't pass or stop, so there are also no warnings and errors.

Has anyone succeeded in using the 0.11.0 version?

**Comment by abigliar** [comment]
#165 #168

**Comment by sergey-volkov-lm** [comment]
> SMB2_IOCTL returned 3221225485 (3221225485/3221225485): expected=[STATUS_SUCCESS, STATUS_BUFFER_OVERFLOW]

Gone for me after upgrading smbj to 0.11.5
