### ISSUE TITLE
NetrShareEnum returned error code: 5 (ERROR_ACCESS_DENIED)

### ISSUE THREAD

**Issue by vasilwnag** [rapid7/smbj-rpc#24]
when use this library to get share forder on win10 smb2 , I get this exception  NetrShareEnum returned error code: 5 (ERROR_ACCESS_DENIED)

**Comment by vasilwnag** [comment]
I have solved this problem, edit  ServerService.java
`final NetrShareEnumRequest request = new NetrShareEnumRequest(2, resumeHandle.getValue());`
to
`final NetrShareEnumRequest request = new NetrShareEnumRequest(1, resumeHandle.getValue());`

**Comment by bli-r7** [comment]
@vasilwnag I opened https://github.com/rapid7/smbj-rpc/issues/30 to address this.
