### ISSUE TITLE
Resolve SID to names rpc request support?

### ISSUE THREAD

**Issue by djdkedev** [rapid7/smbj-rpc#27]
Does smbj-rpc library support "LsarLookupSids (Opnum 15)" operation to resolve SID to names? 
Refer: https://msdn.microsoft.com/en-us/library/cc234488.aspx

**Comment by bli-r7** [comment]
@djdkedev We don't have it yet, LSA support is currently being worked on.

**Comment by bli-r7** [comment]
@djdkedev LSA support has been added in 0.6.0
