### ISSUE TITLE
Create and delete service

### ISSUE THREAD

**Issue by dspurling** [rapid7/smbj-rpc#90]
Do you have any plans to add create or delete service?  I have a local branch with those changes.

**Comment by skhare-r7** [comment]
I have not looked into these two methods; but if you have a local branch that has implemented these already, feel free to open a PR.

**Comment by dspurling** [comment]
Thank you @skhare-r7, but when I try to push I get a permission denied error.

**Comment by bli-r7** [comment]
@dspurling You should be able to fork this repository and create a PR to this from your forked repository.

**Comment by dspurling** [comment]
Thank you @bli-r7.
